output_dir: checkpoints/sft_run

max_length: 1024
num_train_epochs: 1.0

per_device_train_batch_size: 2
gradient_accumulation_steps: 1

learning_rate: 1.0e-4
lr_scheduler_type: cosine
warmup_ratio: 0.03
weight_decay: 0.01
optim: adamw_torch_fused
max_grad_norm: 1.0

bf16: true
gradient_checkpointing: true

completion_only_loss: true # only the assistent output tokens should contribute to the training objective
packing: false
remove_unused_columns: false # the trainer shouldn't automatically throw away columns it does not recognize, because multimodal training often needs them later
dataset_kwargs:
    skip_prepare_dataset: true # do not let SFTTrainer transform the dataset automatically with a different training format first

eos_token: "<|im_end|>"

logging_steps: 10
save_strategy: "no"
report_to: "none"
